### ISSUE TITLE
Crash on Comatose.wad

### ISSUE THREAD

**Issue by Kroc** [zokum-no/zokumbsp#11]
[Comatose.wad](https://www.doomworld.com/idgames/levels/doom2/Ports/a-c/comatose) is a very. very large WAD that pushes the absolute limit of the WAD format. Naturally, it's a great stress test for ZokumBSP; so much so it crashes:

```
working on: Comatose.wad

  MAP01   : GEOMETRY - 63994/65535 lines      Reduced to: 97.65%  14.675 secs
            BLOCKMAP - * Level too big to create valid BLOCKMAP *4274.265 secs
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Options used were: `-bco=3sg=2 -n2ui`

**Comment by zokum-no** [comment]
This isn't a valid Doom map. It is made with an extension of the Doom wad format. You need PRBoom and different tools to play and build this map.

The blockmap is about 294k, that can be handled within the specs. The 144k segs though, that can not be reduced down to 65k. Still, I might add non-doom support for building such behemoth maps one day. It looks like this is a nice test candidate.

**Comment by Kroc** [comment]
Thanks for having a look, appreciated!
